namespace Berca_Backend.Services.Interfaces
{
    /// <summary>
    /// Interface for background job service
    /// Defines scheduled tasks and background operations
    /// </summary>
    public interface IBackgroundJobService
    {
        /// <summary>
        /// Daily job to auto-generate calendar events
        /// </summary>
        Task AutoGenerateCalendarEventsDaily();

        /// <summary>
        /// Weekly job to clean up old auto-generated events
        /// </summary>
        Task CleanupOldAutoGeneratedEvents();

        /// <summary>
        /// Hourly job to send pending event reminders
        /// </summary>
        Task SendPendingEventReminders();

        /// <summary>
        /// Test job for verification
        /// </summary>
        Task TestBackgroundJob();
    }
}
